version: 2
updates:
- package-ecosystem: npm
  directory: "/packages/netlify-cms"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  assignees:
  - d4rekanguok
  ignore:
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
    - 4.4.1
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.1
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.4
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.2
    - 5.24.4
    - 5.26.0
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.32.0
    - 5.34.0
  - dependency-name: "@emotion/styled-base"
    versions:
    - 11.0.0
  - dependency-name: style-loader
    versions:
    - 2.0.0
